Bump Gradle Enterprise Gradle plugin to 3.13
gradle/gradle-enterprise-build-validation-scripts pull request #404
Opened 2023-04-13 09:05 UTC by runningcode

in `gradle.sh` script

2023-04-13 12:16 UTC, etiennestuder commented on components/scripts/lib/gradle.sh
> +    args+=("-Dcom.gradle.enterprise.build-validation.gradle-enterprise.plugin.version=3.13")
Fyi, making the injected plugin/extension version configurable is already on the list and almost ready (just the user config part is missing).

2023-05-04 13:14 UTC, clayburn requested changes
This is now out of date due to the release of Gradle Enterprise Gradle Plugin.

I'm going to mark this with `Request changes` just so it doesn't get inadvertently merged. It sounds like this PR may wind up not being merged anyways.

2023-05-04 13:14 UTC, clayburn commented on components/scripts/lib/gradle.sh
> +    args+=("-Dcom.gradle.enterprise.build-validation.gradle-enterprise.plugin.version=3.13")
`3.13` is no longer the most recent version (`3.13.1` as of today).

2023-05-12 08:39 UTC, runningcode commented
Closing in favor of: https://github.com/gradle/gradle-enterprise-build-validation-scripts/pull/439

2023-05-12 08:39 UTC, closed without merging