Attach experiment receipts to the GH workflow and add build scan links as annotations
gradle/gradle-enterprise-build-validation-scripts pull request #82
Opened 2022-05-02 13:11 UTC by jprinet

2022-05-02 13:12 UTC, jprinet commented
Here is a glimpse of the outcome
https://github.com/jprinet/gradle-enterprise-oss-projects/actions/runs/2258014608

2022-05-03 03:45 UTC, etiennestuder requested changes
One request for a renaming in all 3 actions. The PR can then be merged straight to main (after revasing to main first).

2022-05-03 03:45 UTC, etiennestuder commented on .github/actions/gradle/experiment-1/action.yml
> +        name: receipt-experiment-1
Please rename to `experiment-1-receipt`

2022-05-03 03:45 UTC, etiennestuder commented on .github/actions/gradle/experiment-2/action.yml
> +        name: receipt-experiment-2
Please rename to `experiment-2-receipt`

2022-05-03 03:45 UTC, etiennestuder commented on .github/actions/gradle/experiment-3/action.yml
> +        name: receipt-experiment-3
Please rename to `experiment-3-receipt`

2022-05-03 07:37 UTC, merged